### ISSUE TITLE
Missing description of Clerk job bonuses from Interstellar Franchising

### ISSUE THREAD

**Issue by sztrzask** [OldEnt/stellaris-habitat-start-amaryllis#2]
From steam page

sztrzask
> Prosperity -> Interstellar Franchising (City districts provide +1 Clerk Job) gives my habitats flat +5 Clerk Jobs, is that intended?

OldEnt
> Interstellar Franchising will give you +1 clerk job per *industrial* district built and +5 clerks on any habitatble structure with active habitat captain.

sztrzask
> Cool - Since you have a github, I can add the explanation somewhere so you don't have to do all the work ;-) What do you think about Habitat Captain tooltip? Or perhaps I could switch it to a effect/feature that is automatically added to all owned habitats? Actually let's move this discussion to github, I'll open an issue and we can discuss it there

**Comment by sztrzask** [comment]
I think the best solution would be to add either planetary feature or either planetary modifier for the +5 jobs and edit "industrial" districts if tooltips if it's possible- would you agree? Are there any other hidden bonuses? 

I can start working on planetary features or modifiers right away.

**Comment by sztrzask** [comment]
I was also thinking about going vanilla perk description route - add a triggered event that would replace Habitation District (vanilla) with Habitation District (custom), that gives +1 clerk job per district? 

I think it should be possible to do it? What do you think? I could extend the same mechanism that adds Habitat Captain Quarters planet modifier to do district switcheroo?

I'd have to edit vanilla district though.

**Comment by OldEnt** [comment]
Vanilla districts will always be visible, unless you edit vanilla files and I don't want that. Not touching vanilla is a must for me. I don't want to deal with *can you make compatibility patch with x* and tracking updates from dozens of mods which change the same file (a lot of mods change districts). Paradox is already working on making districts more moddable for this specific reason so there's no reason to lockpick the door which will soonbe  opened.

I can add Interstellar Franchising +5 explanation to the Habitat Captain Quarters modifier description since it is always visible on the top on every habitat and the jobs depend on active captain.

Industrial tooltip could use update to account for +1 clerk from Interstellar Franchising. The same should apply to the trading districts once I add them.

**Comment by OldEnt** [comment]
[Added effects description](https://github.com/OldEnt/stellaris-habitat-start-amaryllis/commit/d5d02f611120540974adca3132cff9d0996fde66#diff-93cec81d9420cb00cfc193a213870acb) via [Update: 26 Apr @ 4:36am on Steam]( https://steamcommunity.com/sharedfiles/filedetails/changelog/1961367151)

![desc2](https://user-images.githubusercontent.com/11807024/80297805-9560ce80-877e-11ea-86c8-dec9d0a04a0c.png)
![desc1](https://user-images.githubusercontent.com/11807024/80297806-95f96500-877e-11ea-9045-389585e8bb62.png)

**Comment by OldEnt** [comment]
Feature added as requested. Thank you!
